import requests
import json

# URL базового адреса Django-сервера
BASE_URL = 'http://127.0.0.1:8001/api'  # Обновлено на порт 8001

def test_api():
    # Создадим тестовый zip-файл для тестирования ИИ функциональности
    import zipfile
    import io
    
    print("=== Testing Create Config with AI ===")
    # Создаем тестовый zip-файл в памяти
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
        zip_file.writestr("file1.txt", "content of file 1")
        zip_file.writestr("file2.yaml", "content of file 2")
        zip_file.writestr("config/settings.json", "content of settings")
    
    zip_buffer.seek(0)
    
    # Отправляем запрос с zip-файлом и промптом
    files = {'file': ('test.zip', zip_buffer, 'application/zip')}
    data = {
        'prompt': 'Create a Docker configuration for this project',
        'name': 'AI Generated Config',
        'description': 'Configuration generated by AI',
        'vcs_type': 'github',
        'temperature': 0.7
    }
    
    response = requests.post(f'{BASE_URL}/create/', files=files, data=data)
    print(f"Create config with AI response: {response.status_code}")
    print(f"Response data: {response.json()}")
    
    # Тест обычного создания конфигурации (для сравнения)
    print("\n=== Testing Create Config (traditional) ===")
    config_data = {
        "name": "Test Config",
        "description": "A test configuration",
        "files": ["file1.txt", "file2.yaml"],
        "meta_config": {
            "vcs_type": "github",
            "temperature": 0.5
        }
    }
    response = requests.post(f'{BASE_URL}/create/', json=config_data)
    print(f"Create config response: {response.status_code}, {response.json()}")
    
    # Тест деплоя
    print("\n=== Testing Deploy ===")
    response = requests.post(f'{BASE_URL}/deploy/')
    print(f"Deploy response: {response.status_code}, {response.json()}")
    
    # Получим ID созданной конфигурации для дальнейших тестов
    config_id = None
    if response.status_code == 200 and 'config_id' in response.json():
        # Сначала создадим конфигурацию заново, чтобы получить ID
        response = requests.post(f'{BASE_URL}/create/', json=config_data)
        if response.status_code == 200:
            config_id = response.json()['config_id']
            print(f"Created config with ID: {config_id}")
    
    # Если не получили ID, создадим конфигурацию заново
    if not config_id:
        response = requests.post(f'{BASE_URL}/create/', json=config_data)
        if response.status_code == 200:
            config_id = response.json()['config_id']
            print(f"Created config with ID: {config_id}")
    
    # Тест ask
    print("\n=== Testing Ask ===")
    if config_id:
        ask_data = {
            "config_id": config_id,
            "content": "This is a question for the model",
            "files": ["http://example.com/file1.txt"]
        }
        response = requests.post(f'{BASE_URL}/ask/', json=ask_data)
        print(f"Ask response: {response.status_code}")
        print(f"Response data: {response.json()}")
    
    # Тест получения всех конфигураций
    print("\n=== Testing Get All Configs ===")
    response = requests.get(f'{BASE_URL}/all-configs/')
    print(f"Get all configs response: {response.status_code}")
    data = response.json()
    print(f"Number of configs: {len(data['configs'])}")
    if data['configs']:
        print(f"First config has {len(data['configs'][0].get('messages', []))} messages")
    
    # Тест получения сообщений для конфигурации
    print("\n=== Testing Get Config Messages ===")
    if config_id:
        response = requests.get(f'{BASE_URL}/config-messages/{config_id}/')
        print(f"Get config messages response: {response.status_code}")
        print(f"Messages data: {response.json()}")

def clear_database():
    import os
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cfg_back.settings')
    import django
    django.setup()
    
    from config_app.models import NewConfig, Message, MetaConfig
    # Удаляем все сообщения (сначала, так как есть связи с NewConfig)
    Message.objects.all().delete()
    # Удаляем все конфигурации
    NewConfig.objects.all().delete()
    # Удаляем все мета-конфигурации
    MetaConfig.objects.all().delete()


if __name__ == "__main__":
    test_api()
    print("\n=== Clearing database ===")
    clear_database()
    print("Database cleared successfully")

if __name__ == "__main__":
    test_api()