# Generated by Django 5.2.6 on 2025-09-27 09:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcs_type', models.CharField(choices=[('github', 'Github'), ('gitlab', 'Gitlab')], max_length=20)),
                ('temperature', models.FloatField()),
                ('orchestration', models.CharField(choices=[('docker', 'Docker'), ('kuber', 'Kubernetes')], max_length=20)),
                ('logging', models.CharField(choices=[('metricbeat', 'Metricbeat'), ('logstash', 'Logstash'), ('grafana', 'Grafana')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('files', models.JSONField()),
                ('github_link', models.URLField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_app.metaconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('model', 'Model'), ('user', 'User')], max_length=10)),
                ('content', models.TextField()),
                ('files', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='config_app.newconfig')),
            ],
        ),
    ]
