# Generated by Django 5.2.6 on 2025-09-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newconfig',
            name='github_link',
        ),
    ]
