# Generated by Django 5.2.6 on 2025-09-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0002_remove_newconfig_github_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaconfig',
            name='logging',
        ),
        migrations.RemoveField(
            model_name='metaconfig',
            name='orchestration',
        ),
    ]
