from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.utils.decorators import method_decorator
from django.views import View
from .models import OrchestrationEnum, VcsEnum, LoggingEnum, MetaConfig, NewConfig, Message
import json
from django.views.decorators.csrf import ensure_csrf_cookie


@csrf_exempt
def create_config_view(request):
    if request.method == 'POST':
        try:
            # Проверяем, является ли запрос multipart/form-data (с файлами)
            if request.content_type.startswith('multipart/form-data'):
                # Обработка запроса с файлом
                if 'file' not in request.FILES:
                    return JsonResponse({'error': 'File is required'}, status=400)
                
                uploaded_file = request.FILES['file']
                
                # Проверяем, что это zip-файл
                if not uploaded_file.name.endswith('.zip'):
                    return JsonResponse({'error': 'Only zip files are allowed'}, status=400)
                
                # Получаем prompt из POST данных
                prompt = request.POST.get('prompt', '')
                if not prompt:
                    return JsonResponse({'error': 'Prompt is required'}, status=400)
                
                # Получаем другие параметры из POST данных
                name = request.POST.get('name', 'Generated Config')
                description = request.POST.get('description', 'Configuration generated by AI')
                
                # Валидация meta_config
                vcs_type = request.POST.get('vcs_type', 'github')
                temperature = float(request.POST.get('temperature', 0.5))
                
                # Сохраняем временно файл
                import os
                from django.conf import settings
                
                upload_dir = os.path.join(settings.MEDIA_ROOT, 'temp')
                os.makedirs(upload_dir, exist_ok=True)
                
                temp_file_path = os.path.join(upload_dir, uploaded_file.name)
                with open(temp_file_path, 'wb+') as destination:
                    for chunk in uploaded_file.chunks():
                        destination.write(chunk)
                
                # Обрабатываем файл с помощью ИИ
                from .ai_client import AIClient
                ai_client = AIClient()
                ai_result = ai_client.process_config_request(temp_file_path, prompt)
                
                # Удаляем временный файл
                os.remove(temp_file_path)
                
                if not ai_result['success']:
                    return JsonResponse({'error': ai_result['content']}, status=500)
                
                # Создание или получение MetaConfig
                meta_config = MetaConfig.objects.create(
                    vcs_type=vcs_type,
                    temperature=temperature
                )

                # Создание NewConfig
                new_config = NewConfig.objects.create(
                    name=name,
                    description=description,
                    files=ai_result['file_structure'],  # Используем структуру файлов из ИИ
                    meta_config=meta_config
                )
                
                # Создаем сообщение от ИИ
                ai_message = Message.objects.create(
                    author='model',
                    content=ai_result['content'],
                    files=[],  # Пока пустой список, можно добавить файлы, если ИИ возвращает
                    config=new_config
                )
                
                return JsonResponse({
                    'message': 'Configuration created successfully',
                    'config_id': new_config.id,
                    'ai_response': ai_result['content'],
                    'file_structure': ai_result['file_structure']
                })
            else:
                # Обработка обычного JSON-запроса
                data = json.loads(request.body)

                # Валидация обязательных полей
                required_fields = ['name', 'description', 'files', 'meta_config']
                for field in required_fields:
                    if field not in data:
                        return JsonResponse({'error': f'{field} is required'}, status=400)

                # Создание или получение MetaConfig
                meta_config_data = data['meta_config']
                meta_config = MetaConfig.objects.create(
                    vcs_type=meta_config_data['vcs_type'],
                    temperature=meta_config_data['temperature']
                )

                # Создание NewConfig
                new_config = NewConfig.objects.create(
                    name=data['name'],
                    description=data['description'],
                    files=data['files'],
                    meta_config=meta_config
                )

                return JsonResponse({
                    'message': 'Configuration created successfully',
                    'config_id': new_config.id
                })
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Invalid JSON'}, status=400)
        except KeyError as e:
            return JsonResponse({'error': f'Missing required field: {str(e)}'}, status=400)
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)
    else:
        return JsonResponse({'error': 'Only POST method allowed'}, status=405)


@csrf_exempt
@require_http_methods(["POST"])
def deploy_config_view(request):
    # Заглушка для деплоя
    return JsonResponse({'message': 'Deploy endpoint - draft implementation'})


@csrf_exempt
@require_http_methods(["POST"])
def ask_config_view(request):
    try:
        data = json.loads(request.body)
        
        # Проверяем обязательные поля
        required_fields = ['config_id', 'content']
        for field in required_fields:
            if field not in data:
                return JsonResponse({'error': f'{field} is required'}, status=400)
        
        # Проверяем, что автор по умолчанию - 'user', если не указан
        author = data.get('author', 'user')
        if author not in ['model', 'user']:
            return JsonResponse({'error': 'Author must be either "model" or "user"'}, status=400)
        
        # Получаем конфигурацию
        try:
            config = NewConfig.objects.select_related('meta_config').get(id=data['config_id'])
        except NewConfig.DoesNotExist:
            return JsonResponse({'error': 'Configuration not found'}, status=404)
        
        # Получаем список файлов (если есть)
        files = data.get('files', [])
        
        # Создаем сообщение от пользователя
        user_message = Message.objects.create(
            author='user',
            content=data['content'],
            files=files,
            config=config
        )
        
        # Здесь может быть интеграция с AI моделью, пока создаем фиктивный ответ от модели
        model_message = Message.objects.create(
            author='model',
            content=f"Это ответ от модели на ваше сообщение: '{data['content']}'",
            files=[],  # Модель может вернуть файлы, но пока пустой список
            config=config
        )
        
        # Возвращаем ответ от модели
        response_data = {
            'message_id': model_message.id,
            'author': model_message.author,
            'content': model_message.content,
            'files': model_message.files,
            'created_at': model_message.created_at.isoformat() if model_message.created_at else None,
            'meta_config': {
                'vcs_type': config.meta_config.vcs_type,
                'temperature': config.meta_config.temperature
            }
        }
        
        return JsonResponse(response_data)
    except json.JSONDecodeError:
        return JsonResponse({'error': 'Invalid JSON'}, status=400)
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)


@csrf_exempt
@require_http_methods(["GET"])
def get_all_configs_view(request):
    # Получение списка всех конфигураций
    configs = NewConfig.objects.select_related('meta_config').prefetch_related('messages')
    
    configs_data = []
    for config in configs:
        config_data = {
            'id': config.id,
            'name': config.name,
            'description': config.description,
            'files': config.files,
            'created_at': config.created_at.isoformat() if config.created_at else None,
            'meta_config': {
                'vcs_type': config.meta_config.vcs_type,
                'temperature': config.meta_config.temperature
            },
            'messages': [
                {
                    'id': message.id,
                    'author': message.author,
                    'content': message.content,
                    'files': message.files,
                    'created_at': message.created_at.isoformat() if message.created_at else None
                }
                for message in config.messages.all()
            ]
        }
        configs_data.append(config_data)
    
    return JsonResponse({'configs': configs_data})





@csrf_exempt
@require_http_methods(["GET"])
def get_config_messages_view(request, config_id):
    try:
        # Получаем конфигурацию
        config = NewConfig.objects.select_related('meta_config').get(id=config_id)
        
        messages = Message.objects.filter(config=config).order_by('created_at')
        
        messages_data = []
        for message in messages:
            message_data = {
                'id': message.id,
                'author': message.author,
                'content': message.content,
                'files': message.files,
                'created_at': message.created_at.isoformat() if message.created_at else None
            }
            messages_data.append(message_data)
        
        return JsonResponse({
            'config_id': config.id,
            'config_name': config.name,
            'meta_config': {
                'vcs_type': config.meta_config.vcs_type,
                'temperature': config.meta_config.temperature
            },
            'messages': messages_data
        })
    except NewConfig.DoesNotExist:
        return JsonResponse({'error': 'Configuration not found'}, status=404)
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)


@csrf_exempt
def upload_file_view(request):
    if request.method == 'POST':
        try:
            # Проверяем, что файл был загружен
            if 'file' not in request.FILES:
                return JsonResponse({'error': 'No file provided'}, status=400)
            
            uploaded_file = request.FILES['file']
            
            # Создаем директорию для хранения файлов, если её нет
            import os
            from django.conf import settings
            
            upload_dir = os.path.join(settings.MEDIA_ROOT, 'uploads')
            os.makedirs(upload_dir, exist_ok=True)
            
            # Сохраняем файл
            file_path = os.path.join(upload_dir, uploaded_file.name)
            with open(file_path, 'wb+') as destination:
                for chunk in uploaded_file.chunks():
                    destination.write(chunk)
            
            # Возвращаем URL для скачивания файла
            file_url = f"{request.build_absolute_uri('/media/uploads/')}{uploaded_file.name}"
            
            return JsonResponse({
                'message': 'File uploaded successfully',
                'file_url': file_url,
                'file_name': uploaded_file.name
            })
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)
    
    return JsonResponse({'error': 'Only POST method allowed'}, status=405)


def download_file_view(request, filename):
    import os
    from django.conf import settings
    from django.http import HttpResponse, Http404
    from django.shortcuts import get_object_or_404
    
    # Путь к файлу
    file_path = os.path.join(settings.MEDIA_ROOT, 'uploads', filename)
    
    if os.path.exists(file_path):
        with open(file_path, 'rb') as file:
            response = HttpResponse(file.read(), content_type='application/octet-stream')
            response['Content-Disposition'] = f'attachment; filename="{filename}"'
            return response
    else:
        raise Http404("File does not exist")


def serve_uploaded_file(request, filename):
    import os
    from django.conf import settings
    from django.http import HttpResponse, Http404
    from django.views.static import serve
    
    file_path = os.path.join(settings.MEDIA_ROOT, 'uploads')
    
    if os.path.exists(os.path.join(file_path, filename)):
        return serve(request, filename, document_root=file_path)
    else:
        raise Http404("File does not exist")
